### ISSUE TITLE
Missing syntax highlight features

### ISSUE THREAD

**Issue by leosdad** [eseom/nunjucks-template#10]
I believe this extension should highlight `{{`, `}}`, `{%`, `%}` like e.g. [this one](https://marketplace.visualstudio.com/items?itemName=ronnidc.nunjucks). Thanks!

**Comment by eseom** [comment]
sorry for super late. thanks. i will apply it

**Comment by eseom** [comment]
ed386845a6d983a738626d4e2c0ab033be527771

**Comment by leosdad** [comment]
Great, thanks!

**Comment by leosdad** [comment]
One note, though. If I disable the [Nunjucks](https://github.com/ronnidc/vscode-nunjucks) extension, the delimiters look exactly like comments (i.e. green). Is this the intended behavior?

**Comment by eseom** [comment]
yes it was intended, i thought it would be more natural for the delimiters to look like comments.
but i wanna hear some opinions
