### ISSUE TITLE
Allow multiline frontmatter

### ISSUE THREAD

**Issue by mjmaurer** [eseom/nunjucks-template#14]
This extension currently inlines any frontmatter at the beginning of the template.

This can cause issues like: https://github.com/11ty/eleventy/issues/1208

It would be great if frontmatter could be properly formatted or ignored.

**Comment by eseom** [comment]
figured it out. I'll add the feature

**Comment by mjmaurer** [comment]
amazing response time thanks! if you had a paypal / payment link i'd chip in some support fyi

**Comment by eseom** [comment]
thanks. just a STAR to this repository will be enough :)
i think it works well at 0.3.1
2c2ceb9354fb6f31166a304721224c5b1eacdae2
