### ISSUE TITLE
autocorrect changing case on format

### ISSUE THREAD

**Issue by KyleMit** [eseom/nunjucks-template#17]
You can repro with a new file named `index.njk` with the following contents:

```html
<pre>{{item.codeJs}}</pre>
```

On format, the extension changes the casing on `codeJs` to `codejs`

Specifically, looks like this is an issue when calling [prettydiff2](https://www.npmjs.com/package/prettydiff2):

```js
const prettydiff = require("prettydiff2");

const input = "<pre>{{item.codeJs}}</pre>";

const output = prettydiff({
  source: input,
  lang: "twig",
  mode: "beautify"
});

console.log({ input, output });
// input:  '<pre>{{item.codeJs}}</pre>'
// output: '<pre>{{item.codejs}}</pre>'
```

Looks like [prettydiff languages](https://prettydiff.com/documentation.xhtml#languages) has support for both `twig` and `nunjucks`.  

Updating [`extension.ts:13`](https://github.com/eseom/nunjucks-template/blob/cc5df1d/src/extension.ts#L13) seems to fix it

```diff
-     lang: "twig",
+     lang: "nunjucks",
```

**Comment by eseom** [comment]
resolved at 0.3.3
