### ISSUE TITLE
Formatter break if hyphen (-) character inside string

### ISSUE THREAD

**Issue by hihahihahoho** [eseom/nunjucks-template#21]
if i remove these 2 dashes inside string then formatter work
![image](https://user-images.githubusercontent.com/29968144/106480318-db9d4800-64dd-11eb-9046-c439550b2d54.png)

**Comment by eseom** [comment]
0.3.4 updated prettydiff does not do anything to the code
Could you test it again at 0.3.4?

**Comment by hihahihahoho** [comment]
> 0.3.4 updated prettydiff does not do anything to the code
> Could you test it again at 0.3.4?

Unfortunately not, i test it again in version 0.4.1

**Comment by eseom** [comment]
cannot reproduce
