### ISSUE TITLE
Version v0.3.4 issue with HTML coloring

### ISSUE THREAD

**Issue by nicewaytodoit** [eseom/nunjucks-template#27]
Since the version v0.3.4 my project has lost HTML coloring, nunjuck template syntax still works but not html. There is nothing in output or problem tab that may lead me to the cause of the issue.
Is there something I need to configure additionally for this update?

Tried reverting to v0.3.1 - this one works.

### System info
VSCODE Version: 1.54.1 (system setup)
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
OS: Windows_NT x64 10.0.19041

**Comment by RwwL** [comment]
I'm having the same issue. I use the `.nunj` extension for templates, and I do have that configured properly in the `files.associations` settings.

**Comment by nicewaytodoit** [comment]
My extension is .njk and I tried to manually re-configuring (delete save configure save) after update, but that did not help either.

**Comment by SamBrishes** [comment]
Hello,

I had the same issue as well, but I found a working solution after [comparing both versions 0.3.1 and 0.3.4](https://github.com/eseom/nunjucks-template/compare/cc5df1dcd61404477438d0abe7ea081b7772da36..b11cd157cf42a0ba9e495573994b8659d51ed17f):

I changed the `patterns.include` path for the HTML Syntax back from `"include": "text.html.twig"` to `"include": "text.html.basic"` in the extension file `%USERPROFILE%\.vscode\extensions\eseom.nunjucks-template-0.3.4\assets\syntaxes\njk-html.json`.

Sincerely,
Sam.

**Comment by MrRayures** [comment]
Thx for the tips @SamBrishes that works for me !

**Comment by ellocke** [comment]
thank you @SamBrishes , this saved my day!

File path for Ubuntu: `~/.vscode-server/extensions/eseom.nunjucks-template-0.3.4/assets/syntaxes/njk-html.json`

**Comment by eseom** [comment]
sorry Im late, I wonder the settings
```"files.associations": {
  "*.html": "njk"
},``` in `settings.json` did not work after the update??

How could i reproduce this problem??
