### ISSUE TITLE
YAML front matter formatting

### ISSUE THREAD

**Issue by fiqrisr** [eseom/nunjucks-template#29]
When i format the document which has YAML front matter, it becomes like this

![image](https://user-images.githubusercontent.com/30799382/121358430-d0ab6600-c95c-11eb-9950-b172179b227b.png)

**Comment by ellocke** [comment]
FYI: Based on a recent observation, the YAML frontmatter becomes messed up when there's a JavaScript function definition somewhere in the file.

i.e.
``` 
<script>
  function () {
    console.log("test")
  }
</script>
```
is sufficient to make the frontmatter collapse. When I remove the function definition, the frontmatter is preserved. The position of the function definition in the document does not make a difference.

Also, it's **not just** the frontmatter in my case.

`{% include 'footer.njk' %}` will also break into

```
{
  % include 'footer.njk' %
}
```

and ``{{ title }}`` becomes

```
{
  {
    title
  }
}
```

Same is the case with something like: 

```
<button onclick="setTimeout(function() {console.log(this)}, 250)">click me</button>
```

Seems that it has something to do with the single `{` and / or `}`.

**Comment by eseom** [comment]
It will be resolved in next release
