### ISSUE TITLE
HTML Snippets

### ISSUE THREAD

**Issue by Shirimasen** [eseom/nunjucks-template#3]
HTML snippets don't work inside .njk files with this extension.
I expect snippets to work just like in .php files.

**Comment by wottpal** [comment]
Also for me HTML-snippets stop working inside .html files which are not even nunjuck related. Deinstalled until I can set which filetypes should be considered.

**Comment by eseom** [comment]
Sorry for super late.
I have updated codes, market and README.
Thanks :)
