### ISSUE TITLE
Extension is missing in open-vsx.org store

### ISSUE THREAD

**Issue by senarclens** [eseom/nunjucks-template#33]
This extension is not present in the open-vsx.org store, which means that it is missing when trying to install it from any open source vscodium build. Please add it to open-vsx.org when publishing versions. Thank you!

Expected:
searching for "nunjucks" shows this extension so that it can easily be installed

Actual:
searching for "nunjucks" does not show this extension

Note:
There is **no license** file in this repo; if you tell me which license you'd prefer, I can make a PR and add the correct information; MIT? ALv2? Other preferences?

**Comment by izzqz** [comment]
👀 Waiting any progress. I am trying to use this extension on gitpod

**Comment by eseom** [comment]
I will try soon :)

**Comment by eseom** [comment]
please check https://open-vsx.org/extension/eseom/nunjucks-template
