### ISSUE TITLE
How do I enable formatting

### ISSUE THREAD

**Issue by HighSites** [eseom/nunjucks-template#36]
Despite all reinstallations and "editor.defaultFormatter" changes I still get 

> There is no formatter for 'njk' files installed

So, how do I enable it?
Or did I get it wrong & this extension can not serve as a language formatter?

**Comment by eseom** [comment]
Hello,
Please check the version of your vscode and nunjucks-template extension.

mine below
  vscode - Version: 1.72.2 (Universal)
  nunjucks-template v0.5.1

It works without any configuration

**Comment by HighSites** [comment]
The problem was solved without any actions from my side
However, thank you for your reply
