### ISSUE TITLE
Use category "Programming Languages" rather than "Language Packs"

### ISSUE THREAD

**Issue by gregvanl** [eseom/nunjucks-template#4]
The category "Language Packs" is for localized display languages such as German and Japanese. Please use the category "Programming Languages" for extensions that provide programming language features.

![image](https://user-images.githubusercontent.com/12818376/55659840-42555b80-57b8-11e9-82b2-d81d3526c9bc.png)

**Comment by eseom** [comment]
Sorry for super late.
I have updated codes, market and README.
Thanks :)
