### ISSUE TITLE
Make Filetypes configurable

### ISSUE THREAD

**Issue by wottpal** [eseom/nunjucks-template#5]
Hi @eseom,
unfortunately your plugin is currently unusable for me as it conflicts somehow with (all) Angular-Templates Language Packages (`.html`). As I only use `.njk`-files for my Nunjucks-Templates I would like to configure your plugin to only detect these files.

I really hope for your help.

Thanks and regards from Germany :)
Dennis

**Comment by eseom** [comment]
Sorry for super late.
I have updated codes, market and README.
Thanks :)
