### ISSUE TITLE
Support for custom icon via vscode-icons

### ISSUE THREAD

**Issue by KyleMit** [eseom/nunjucks-template#6]
[vscode-icons](https://github.com/vscode-icons/vscode-icons) is a popular way to associate custom icons to files within vs code

However, they match icons by language ids and have historically rejected tickets to update their manifest to include nunjucks by extension:

* [#1819 - Nunjucks icon missing extension .njk](https://github.com/vscode-icons/vscode-icons/issues/1819)
* [#1812 - Icon Request Support for nunjucks .njk](https://github.com/vscode-icons/vscode-icons/issues/1812)
* [#118 - Nunjucks file icon](https://github.com/vscode-icons/vscode-icons/issues/118)

According to their [wiki - list of supported icons](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles):

> Icons that are supported via Language ID, require a syntax highlighting extension [*(like this one)*], that registers that id, to be installed, for the icon to show.

The [available language ids](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#nunjucks) are:

* nunjucks
* nunj
* njs

However this extension registers nunjucks under the abbreviated extension:

* njk

One option is to swap out the language id or maybe add an alias, but I'm not sure how much work this would require.

Another workaround, if you wanted to provide support, is to add a section to the readme settings configuration to add the following setting (according to their [fine tuning](https://github.com/vscode-icons/vscode-icons/wiki/FineTuning) wiki) :

```json
"vsicons.associations.files": [
  { "icon": "nunjucks", "extensions": ["njk"], "format": "svg" }
],
```

And then run **Apply Icon Customization** which should update the icons like this:

![image](https://user-images.githubusercontent.com/4307307/71217134-b2463c00-228a-11ea-8ff3-261c44b810c1.png)

Not a super high priority, and not sure how ubiquitous vscode-icons is amongst other users, but just documenting in case it's helpful

**Comment by eseom** [comment]
I will be watching this issue. I've just updated README.md. Thanks. Welcome any PR.
