### ISSUE TITLE
Broken auto-indent after pressing "Enter" between tags

### ISSUE THREAD

**Issue by alkorlos** [eseom/nunjucks-template#8]
If nunjucks-template is installed, good syntax highlighting appears, but broken auto-indent after pressing "Enter" between tags

I have:
![Z4Rm6](https://user-images.githubusercontent.com/14668230/77129945-55b41200-6a6f-11ea-9255-632509973eb8.gif)
By pressing "Enter", "Shift + Enter" and "Shift".

But I need by pressing "Enter":
![auto-close1](https://user-images.githubusercontent.com/14668230/77129965-6b293c00-6a6f-11ea-9126-cbd03d02e29b.gif)
Like default .html.

Is there a way to fix it?

**Comment by eseom** [comment]
sorry for super late, i did not figured out the solution, i will try

**Comment by alkorlos** [comment]
Thanks for trying.

**Comment by eseom** [comment]
6bcb25e48c726f044de3da1c397bcaec1a2dc5e1
