### ISSUE TITLE
Placeholder contribution endpoints

### ISSUE THREAD

**Issue by csvn** [eseom/nunjucks-template#9]
It seems this extesion has a few unused contributed things in it's `package.json`. I think it would be best to remove the `configuration` and `commands` properties inside `contributes`, since they do not seem to have any purpose?

```jsonc
// package.json
{
  // ...snip...
  "contributes": {
    "commands": [
      {
        "command": "extension.sayHello",
        "title": "Hello World"
      }
    ],
    "configuration": {
      "type": "object",
      "title": "nunjucks-template",
      "properties": {
        "nunjucks-template.sample": {
          "type": "boolean",
          "default": true,
          "description": "a sample configuration"
        }
      }
    }
  }
```
![image](https://user-images.githubusercontent.com/8770194/78155238-7c922100-743d-11ea-9e9d-6fbc9cdc976b.png)

**Comment by eseom** [comment]
sorry for super late, it's just useless things that i did not remove from the sample. i will thank for any PR
